


name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Get Users
        run: curl --location --request GET 'localhost:3001/api/users'
      - name: Post a user
        run: |
          curl --location --request POST 'localhost:4333/api/user' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "username": "phablo210",
              "address": "Rua cecílio batista marques, 242"
          }'
      - name: Get Users after create
        run: curl --location --request GET 'localhost:3001/api/users'
      
